package Tekiz._DPSCalculator._DPSCalculator.model.enums.modifiers;

public enum ModifierTypes
{
	DAMAGE_ADDITIVE,
	DAMAGE_MULTIPLICATIVE,
	PENETRATION_PHYSICAL,
	PENETRATION_ENERGY,
	PENETRATION_RADIATION,
	PENETRATION_POISON,
	ATTACKSPEED,
	RELOADSPEED,
	ACCURACY,
	RANGE,
	SNEAK,
	CRITICAL,
	SPECIAL_STRENGTH,
	SPECIAL_PERCEPTION,
	SPECIAL_ENDURANCE,
	SPECIAL_CHARISMA,
	SPECIAL_INTELLIGENCE,
	SPECIAL_AGILITY,
	SPECIAL_LUCK,
	MUTATION;
}
