package Tekiz._DPSCalculator._DPSCalculator.model.enums;

public enum BonusTypes
{
	DAMAGE_ADDITIVE,
	DAMAGE_MULTIPLICATIVE,
	PENETRATION_PHYSICAL,
	PENETRATION_ENERGY,
	PENETRATION_RADIATION,
	PENETRATION_POISON,
	ATTACKSPEED,
	RELOADSPEED,
	ACCURACY,
	RANGE,
	SNEAK,
	CRITICAL,
	CONSUMABLE,
	SPECIAL,
	MUTATION;
}
