package Tekiz._DPSCalculator._DPSCalculator.model.enums;

public enum PerkTypes
{
	DAMAGE,
	PENETRATION,
	ATTACKANDRELOADSPEED,
	ACCURACYANDRANGE,
	SNEAKBONUS,
	CRITICALBONUS,
	CONSUMABLE,
	SPECIAL,
	MUTATION;
}
